schema_version = "1.0.2"

id = "cherub_suite"
version = "1.0.2"
name = "Cherub Suite"
tagline = "Common pie menu helpers & Asset Library authoring utilities"
maintainer = "Luis Cherubini"
type = "add-on"
website = "https://github.com/luischerub/Cherub-Suite"

blender_version_min = "5.0.0"

license = ["SPDX:GPL-3.0-or-later"]
categories = ["Modeling"]
tags = ["Mesh", "Modeling", "Pipeline"]

[permissions]
files = "write"
