schema_version = "1.0.0"
id = "cherub_suite"
version = "0.2.0"
name = "Cherub Suite"
tagline = "Advanced mecha and hard-surface design utility"
maintainer = "Luís Cherubini"
type = "add-on"
blender_version_min = "4.2.0"
license = ["GPL-2.0-or-later"]
website = "https://github.com/luischerub/Cherub-Suite"
categories = ["Modeling"]
tags = ["Modeling", "UV", "Pie Menu", "Workflow"]

[permissions]
# If your operators need to save files or talk to the web, list them here.