schema_version = "1.0.0"

id = "cherub_suite"
version = "0.3.2"
name = "Cherub Suite"
tagline = "Advanced hard-surface design & pipeline utility"
maintainer = "Luis Cherubini"
type = "add-on"
website = "https://github.com/luischerub/Cherub-Suite"

blender_version_min = "5.0.0"

license = ["GPL-3.0-or-later"]
categories = ["Modeling"]
tags = ["User Interface", "Mesh", "Modeling", "Pipeline"]

[permissions]
